spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.52.112.29:3306/db_payrollsystem?characterEncoding=UTF-8
    username: Admin
    password: Admin123!
server:
  port: 8888

logging:
  level:
    root: info
    com.tomorrow.dao: debug