spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.52.112.29:3306/db_payrollsystem?characterEncoding=UTF-8
    username: Admin
    password: Admin123!
  redis:
    host: 192.168.31.130
    port: 6379
    pool:
      max-active: 100
      max-idle: 10
      max-wait: 100000
    timeout: 1000
server:
  port: 8888

logging:
  level:
    root: info
    com.tomorrow.dao: debug